### ISSUE TITLE
## Attention! The library doesn't work with AOT compiler. ?

### ISSUE THREAD

**Issue by Dashing-Daniel-Li** [andreypelykh/angular-bounce#1]
Any reason why it doesn't work. Id be keen to help you find a solution to this. Is a pretty good library. Using it in my ionic project but it fails to build for mobiles because of the AOT issue

**Comment by andreypelykh** [comment]
Hello, @crazypigs ! Sorry for the late response. I've just updated the library and now it works with AOT compilation. Hope it can be helpful for you :)

**Comment by MattiJarvinen** [comment]
Remember to close the issue if it's already solved.

**Comment by andreypelykh** [comment]
@MattiJarvinen-BA Good tip, thanks.
